version: 0.0
os: linux
files:
  - source: JobManagement_CODEBUILD.war
    destination: /opt/tomcat10/webapps/
hooks:
  ApplicationStop:
    - location: scripts/stop_tomcat.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/backup_current.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/restart_tomcat.sh
      timeout: 300
      runas: root
  RollBack:
    - location: scripts/rollback.sh
      timeout: 300
      runas: root