version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo "Fetching SSH Key from AWS Secrets Manager..."
      - aws secretsmanager get-secret-value --secret-id MyServerSSHKey_3 --query SecretString --output text > key.pem
      - sed -i 's/\\n/\n/g' key.pem
      - grep -q "BEGIN RSA PRIVATE KEY" key.pem || sed -i '1i-----BEGIN RSA PRIVATE KEY-----' key.pem
      - grep -q "END RSA PRIVATE KEY" key.pem || echo "-----END RSA PRIVATE KEY-----" >> key.pem
      - chmod 400 key.pem
      - export PIPELINE_START=$(date +%s)

  build:
    commands:
      - echo "Building Job Management System..."
      - mkdir -p build/WEB-INF/classes
      # Compile with error capture
      - javac -cp "src/main/webapp/WEB-INF/lib/*" -d build/WEB-INF/classes $(find src -name "*.java") 2> compile_error.log || { echo "Build failed!"; exit 1; }
      - cp -R src/main/resources/* build/WEB-INF/classes/
      - cp -R src/main/webapp/* build/
      # Create WAR with validation
      - jar -cvf JobManagement_CODEBUILD.war -C build . || { echo "WAR creation failed!"; exit 1; }
      # Create backup only if build succeeds
      - mkdir -p /tmp/codebuild_backup
      - cp JobManagement_CODEBUILD.war /tmp/codebuild_backup/JobManagement_CODEBUILD.war_bak

  post_build:
    commands:
    # Consolidated deployment block
    - >
      if [ -f JobManagement_CODEBUILD.war ]; then
        # Pre-deployment metrics
        echo "Measuring resource usage BEFORE deployment..."
        vmstat -s | awk '{printf "%.2f MB - %s\n", $1/1024, substr($0, index($0,$2))}' > resource_usage_before.log
        free -h > mem_before.log

        # Deployment timing
        DEPLOY_START=$(date +%s)
        COMMIT_TIME=$(git log -1 --format=%ct)
        LEAD_TIME=$((DEPLOY_START - COMMIT_TIME))

        # Attempt deployment
        if scp -o StrictHostKeyChecking=no -i key.pem JobManagement_CODEBUILD.war ubuntu@40.192.68.176:/opt/tomcat10/webapps/; then
          # Successful deployment
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@40.192.68.176 <<EOF
            sudo rm -rf /opt/tomcat10/webapps/JobManagement_CODEBUILD
            sleep 5
            sudo /opt/tomcat10/bin/shutdown.sh || true
            sudo /opt/tomcat10/bin/startup.sh
          EOF

          # Wait for deployment
          tail -f /opt/tomcat10/logs/catalina.out | while read line; do
            echo "\$line" | grep -q "Deployment of web application archive" && break
          done

          # Post-deployment metrics
          DEPLOY_END=$(date +%s)
          DEPLOY_DURATION=$((DEPLOY_END - DEPLOY_START))
          echo "Deployment took $DEPLOY_DURATION seconds"
        else
          # Rollback logic
          echo "Deployment failed! Rolling back..."
          ROLLBACK_START=$(date +%s)
          
          if [ -f /tmp/codebuild_backup/JobManagement_CODEBUILD.war_bak ]; then
            scp -o StrictHostKeyChecking=no -i key.pem /tmp/codebuild_backup/JobManagement_CODEBUILD.war_bak ubuntu@40.192.68.176:/opt/tomcat10/webapps/JobManagement_CODEBUILD.war
            ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@40.192.68.176 <<EOF
              sudo rm -rf /opt/tomcat10/webapps/JobManagement_CODEBUILD
              sleep 5
              sudo /opt/tomcat10/bin/shutdown.sh || true
              sudo /opt/tomcat10/bin/startup.sh
            EOF
          else
            echo "No backup found! Showing compilation errors:"
            cat compile_error.log
            exit 1
          fi

          ROLLBACK_END=$(date +%s)
          ROLLBACK_DURATION=$((ROLLBACK_END - ROLLBACK_START))
          echo "Rollback completed in $ROLLBACK_DURATION seconds"
          exit 1
        fi

        # Final metrics
        echo "Measuring resource usage AFTER deployment..."
        vmstat -s | awk '{printf "%.2f MB - %s\n", $1/1024, substr($0, index($0,$2))}' > resource_usage_after.log
        free -h > mem_after.log
        PIPELINE_END=$(date +%s)
        TOTAL_PIPELINE_TIME=$((PIPELINE_END - PIPELINE_START))

        # Generate metrics summary
        echo "-------------------------------------------------" > metrics_summary.log
        echo "Total Pipeline Time: $TOTAL_PIPELINE_TIME seconds" >> metrics_summary.log
        echo "Deployment Duration: $DEPLOY_DURATION seconds" >> metrics_summary.log
        echo "Lead Time for Changes: $LEAD_TIME seconds" >> metrics_summary.log
        cat mem_before.log mem_after.log >> metrics_summary.log
      else
        echo "Build failed! Compilation errors:"
        cat compile_error.log
        exit 1
      fi

artifacts:
  files:
    - JobManagement_CODEBUILD.war
    - compile_error.log
    - test_results.log
    - metrics_summary.log
    - resource_usage_before.log
    - resource_usage_after.log
    - mem_before.log
    - mem_after.log