version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo "Fetching SSH Key from AWS Secrets Manager..."
      - aws secretsmanager get-secret-value --secret-id MyServerSSHKey --query SecretString --output text > key.pem
      - sed -i 's/\\n/\n/g' key.pem  # Fix newlines
      - echo "Fixing SSH Key Format..."
      - ssh-keygen -p -m PEM -f key.pem -N "" -C ""  # Convert key format
      - chmod 400 key.pem  # Ensure correct permissions
      - ls -lah key.pem  # Debug: Check if the key exists
      - cat key.pem  # Debug: Ensure key is readable
      - echo "Testing SSH Connection..."
      - ssh -vvv -o StrictHostKeyChecking=no -i key.pem ubuntu@18.60.142.88 "echo Connected!"
  build:
    commands:
      - echo "Building Job Management System..."
      - mkdir -p build/WEB-INF/classes
      - javac -cp "src/main/webapp/WEB-INF/lib/*" -d build/WEB-INF/classes $(find src -name "*.java")
      - cp -R src/main/resources/* build/WEB-INF/classes/
      - cp -R src/main/webapp/* build/
      - jar -cvf JobManagement.war -C build .
  post_build:
    commands:
      - echo "Deploying WAR file to Tomcat server..."
      - scp -o StrictHostKeyChecking=no -i key.pem JobManagement.war ubuntu@18.60.142.88:/opt/tomcat10/webapps/
      - ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@18.60.142.88 <<EOF
          pkill -f 'org.apache.catalina.startup.Bootstrap' || true
          sleep 5
          /opt/tomcat10/bin/shutdown.sh || true
          /opt/tomcat10/bin/startup.sh
          exit
        EOF
artifacts:
  files:
    - JobManagement.war

