version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
    - echo "Fetching SSH Key from AWS Secrets Manager..."
    - aws secretsmanager get-secret-value --secret-id MyServerSSHKey_1 --query SecretString --output text > key.pem
    - echo "Fixing newlines in key.pem..."
    - sed -i 's/\\n/\n/g' key.pem  # Replace literal \n with actual newlines
    - echo "Checking header in key.pem..."
    - grep -q "BEGIN RSA PRIVATE KEY" key.pem || sed -i '1i-----BEGIN RSA PRIVATE KEY-----' key.pem
    - echo "Checking footer in key.pem..."
    - grep -q "END RSA PRIVATE KEY" key.pem || echo "-----END RSA PRIVATE KEY-----" >> key.pem
    - chmod 400 key.pem  # Ensure the key has secure permissions
    - ls -lah key.pem  # Debug: List key file details
    - echo "Preview of key.pem (first 5 lines):"
    - head -n 5 key.pem
    - echo "Testing SSH connection..."
    - ssh -vvv -o StrictHostKeyChecking=no -i key.pem ubuntu@18.60.142.88 "echo Connected!"
      
  build:
    commands:
      - echo "Building Job Management System..."
      - mkdir -p build/WEB-INF/classes
      - javac -cp "src/main/webapp/WEB-INF/lib/*" -d build/WEB-INF/classes $(find src -name "*.java")
      - cp -R src/main/resources/* build/WEB-INF/classes/
      - cp -R src/main/webapp/* build/
      - jar -cvf JobManagement.war -C build .
  post_build:
    commands:
      - echo "Deploying WAR file to Tomcat server..."
      - scp -o StrictHostKeyChecking=no -i key.pem JobManagement.war ubuntu@18.60.142.88:/opt/tomcat10/webapps/
      - ssh -tt -o StrictHostKeyChecking=no -i key.pem ubuntu@18.60.142.88 <<EOF
          sudo pkill -f 'org.apache.catalina.startup.Bootstrap' || true
          sleep 5
          sudo /opt/tomcat10/bin/shutdown.sh || true
          sudo /opt/tomcat10/bin/startup.sh
          exit
        EOF
artifacts:
  files:
    - JobManagement.war









