version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo "Fetching SSH Key..."
      - aws secretsmanager get-secret-value --secret-id MyServerSSHKey_3 --query SecretString --output text > key.pem
      - sed -i 's/\\n/\n/g' key.pem
      - chmod 400 key.pem

  build:
    commands:
      - echo "Building..."
      - mkdir -p build/WEB-INF/classes
      - javac -cp "src/main/webapp/WEB-INF/lib/*" -d build/WEB-INF/classes $(find src -name "*.java") 2> compile_error.log || { echo "Build failed!"; exit 1; }
      - cp -R src/main/resources/* build/WEB-INF/classes/
      - cp -R src/main/webapp/* build/
      - jar -cvf JobManagement_CODEBUILD.war -C build . || { echo "WAR creation failed!"; exit 1; }
  post_build:
    commands:
      - >
        if [ -f JobManagement_CODEBUILD.war ]; then
          echo "Build succeeded! Creating backup..."
          scp -o StrictHostKeyChecking=no -i key.pem JobManagement_CODEBUILD.war ubuntu@40.192.33.107:/tmp/codebuild_bak/JobManagement_CODEBUILD.war_bak
        else  
          echo -e "\nBuild failed - compilation errors:"
          cat compile_error.log
          echo "Rolling back..."
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@40.192.33.107 "
            /opt/tomcat10/bin/catalina.sh stop || true
            cp -f /tmp/codebuild_bak/JobManagement_CODEBUILD.war_bak /opt/tomcat10/webapps/JobManagement_CODEBUILD.war
            /opt/tomcat10/bin/startup.sh
          "
          exit 1
        fi

artifacts:
  files:
    - JobManagement_CODEBUILD.war
    - compile_error.log